### PR TITLE
Handle special characters in bibtex author names.

### LINKED ISSUE #44: Author names with accents are not handled correctly.
The `\'c` in [this bibtex file](http://compneuro.uwaterloo.ca/publications/kajic2016.html#kajic2016cite) [does not get properly displayed as ć on the website](http://compneuro.uwaterloo.ca/publications/kajic2016.html#kajic2016cite). Surprisingly the author link is working, but the publication is not listed there.

### PR DESCRIPTION
**Pull request by jgosmann**
Fixes #44.

### CODE REVIEW

**Comment by hunse** [comment]
Could we add this for abstracts, too? See e.g. http://compneuro.uwaterloo.ca/publications/voelker2015.html

**Comment by jgosmann** [comment]
The math equations where already working as long as they are properly enclosed in `$ ... $`. So I added those and than also added decoding of other special characters for titles, abstracts, and keywords. Some abstract had percent signs in them. These need to be properly escaped now and `latexcodec` isn't decoding them, so I had to add a line to let `latexcodec` know about percent signs. I also opened an issue upstream: mcmtroffaes/latexcodec#48

**Comment by Seanny123** [comment]
LGTM.

**Comment by Seanny123** [comment]
Does merging this fix the current website build which is failing for reasons I don't totally understand.

**Comment by Seanny123** [comment]
Do you want to wait until the upstream fix happens or can I merge this after I test it locally?

**Comment by jgosmann** [comment]
I looked into the problems with those other Unicode characters and it seems I can get it all working with a newer version of `pybtex` and the right development branch of `latexcodec`. I'm probably going to update this PR accordingly.

Just not sure whether to wait on a new `latexcodec` version or whether to monkey patch the required changes.

**Comment by tbekolay** [comment]
FYI there was some issue with pybtex 0.18.1, which is why the requirements.txt has a hard dependency on 0.17.1. I don't remember exactly, but I think it was an API change, but perhaps it was an issue that is fixed in newer versions.

It could be that opening files with explicit UTF-8 encoding (`io.open` instead of with the builtin `open` in Python 2) will fix the unicode issue, but I'm not certain.

**Comment by jgosmann** [comment]
It seems to be working with pybtex 0.20. I had to fix a few things because of the API change, but it wasn't a lot.

**Comment by jgosmann** [comment]
Turns out doing this properly is not as simple as it seems at first. The main reason is that the bibtex “codec” is not exactly the same as the LaTeX “codec” implemented by `latexcodec`. The key difference (actually maybe the only difference) is that `%` is not a comment character in bibtex, but `latexcodec` treats it as one. While it is somewhat reasonable to say that all abstracts in the bibtex files should properly escape the percent signs, it is possible to have percent signs in URLs and I would say that they should not be escaped there. But then `latexcodec` will cut off everything after the percent sign.

It would be possible to hack `latexcodec` accordingly, but it is not super straight-forward.

It might be worthwhile to look into projects similar to pybtex like python-bibtexparser to see if these are better suited. (Though I'm not super optimistic that any project gets the conversion of special and unicode characters completely right. It's hard to get a complete solution, but also what I would see as a fundamental feature of such a project.)

**Comment by mcmtroffaes** [comment]
I see two solutions to this: 1. Do not use latexcodec directly on the bibtex file, but instead only use it in post-processing on titles, authors, etc. There was some interest from pybtex to support this, but I'm not sure where that's at. 2. Alternatively, a separate bibtex codec could be implemented. We then need a formal grammar for bibtex, separate from the latex one. Not sure how easy that would be. I think 1. is easier to do (parsing bibtex is rather tricky!).

**Comment by jgosmann** [comment]
I looked at alternatives to pybtex, but no solution provides all required features or gets everything right. Because of that, it seems best to stick with pybtex and fix what it does (which is basically what @mcmtroffaes described as solution 1.). Where we just read out values from the bibtex we have full control over applying the latex decoding anyways and the current version of this PR already adds latex decoding in appropriate places. The problem is currently that we also generate a plain text citation with a style shipped by pybtex that latex decodes all fields. I will create an issue about that upstream. For the time being we can fix this by overwriting the `format_url` function of that style to not apply latex decoding. I will update this PR accordingly.

**Comment by jgosmann** [comment]
This is now ready for another review. :)

**Comment by jgosmann** [comment]
Upstream pybtex issue: https://bitbucket.org/pybtex-devs/pybtex/issues/86/should-not-latex-decode-some-fields

**Comment by Seanny123** [comment]
This built successfully on my local computer, but when I tried to open the web-pages created by `flask` none of the special characters that this pull request was supposed to resolve were rendered.

**Comment by jgosmann** [comment]
That's weird, it definitely works for me. Can you give a concrete example of what does not work?

**Comment by Seanny123** [comment]
Turns out I was running it wrong. Merged and I'm going to edit the README to be more painfully obvious about how to test things.

**Pull request merged**
