### PR TITLE
Create chateau2020.bib

### PR DESCRIPTION
**Pull request by HugoChateauLaurent**
public pdf link should be provided soon

### CODE REVIEW

**Comment by arvoelke** [comment]
> public pdf link should be provided soon

Is the public PDF link available yet? We either include this or a link to the fulltext for all recent publications on compneuro (also I'd like to read it!).

**Comment by HugoChateauLaurent** [comment]
Thanks for your interest :) The organisers said they will make it available before the workshop, which will take place on September 22nd.

**Comment by HugoChateauLaurent** [comment]
@arvoelke I don't know how to upload the file, but I've added the link to the .bib:
https://openreview.net/forum?id=DenHym39bH

**Comment by arvoelke** [comment]
Great! I grabbed it from there and added a commit linking to its location on the compneuro website: http://compneuro.uwaterloo.ca/files/publications/chateau.2020.pdf

Is that okay? If so I'll merge this in. Thanks!

**Comment by HugoChateauLaurent** [comment]
Yes, perfect :)

**Pull request merged**
